services:
  - type: web
    name: dressshop-backend
    runtime: docker
    rootDir: dress-shop/backend
    dockerfilePath: ./Dockerfile
    envVars:
      - key: DB_URL
        sync: false
      - key: DB_USERNAME
        sync: false
      - key: DB_PASSWORD
        sync: false
      - key: ADMIN_USERNAME
        sync: false
      - key: ADMIN_PASSWORD
        sync: false
      - key: ADMIN_TOKEN
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: SERVER_BASE_URL
        sync: false
      - key: CORS_ALLOWED_ORIGIN
        sync: false
      - key: UPLOAD_DIR
        value: ./uploads
